name: Ubuntu Runner

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Check system
        run: |
          uname -a
          lsb_release -a
          pwd
          df -h

      - name: Keep runner alive
        run: sleep 21600
